# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_get_project_members_for_user_api_v1_projects_project_id_members_get(self) -> None:
        """Test case for get_project_members_for_user_api_v1_projects_project_id_members_get

        Get Project Members For User
        """
        pass

    def test_get_projects_api_v1_projects_get(self) -> None:
        """Test case for get_projects_api_v1_projects_get

        Get Projects
        """
        pass


if __name__ == '__main__':
    unittest.main()
