# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.api.sensors_api import SensorsApi


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SensorsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_delete(self) -> None:
        """Test case for delete_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_delete

        Delete Sensor
        """
        pass

    def test_get_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_get(self) -> None:
        """Test case for get_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_get

        Get Sensor
        """
        pass

    def test_list_sensors_api_v1_campaigns_campaign_id_stations_station_id_sensors_get(self) -> None:
        """Test case for list_sensors_api_v1_campaigns_campaign_id_stations_station_id_sensors_get

        List Sensors
        """
        pass

    def test_partial_update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_patch(self) -> None:
        """Test case for partial_update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_patch

        Partial Update Sensor
        """
        pass

    def test_update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_put(self) -> None:
        """Test case for update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_put

        Update Sensor
        """
        pass


if __name__ == '__main__':
    unittest.main()
