# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.models.login_response import LoginResponse

class TestLoginResponse(unittest.TestCase):
    """LoginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoginResponse:
        """Test LoginResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoginResponse`
        """
        model = LoginResponse()
        if include_optional:
            return LoginResponse(
                access_token = '',
                token_type = ''
            )
        else:
            return LoginResponse(
                access_token = '',
                token_type = '',
        )
        """

    def testLoginResponse(self):
        """Test LoginResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
