# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.api.measurements_api import MeasurementsApi


class TestMeasurementsApi(unittest.TestCase):
    """MeasurementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MeasurementsApi()

    def tearDown(self) -> None:
        pass

    def test_create_measurement_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_post(self) -> None:
        """Test case for create_measurement_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_post

        Create Measurement
        """
        pass

    def test_delete_sensor_measurements_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_delete(self) -> None:
        """Test case for delete_sensor_measurements_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_delete

        Delete Sensor Measurements
        """
        pass

    def test_get_measurements_with_confidence_intervals_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_confidence_intervals_get(self) -> None:
        """Test case for get_measurements_with_confidence_intervals_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_confidence_intervals_get

        Get Measurements With Confidence Intervals
        """
        pass

    def test_get_sensor_measurements_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_get(self) -> None:
        """Test case for get_sensor_measurements_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_get

        Get Sensor Measurements
        """
        pass

    def test_partial_update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_measurement_id_patch(self) -> None:
        """Test case for partial_update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_measurement_id_patch

        Partial Update Sensor
        """
        pass

    def test_update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_measurement_id_put(self) -> None:
        """Test case for update_sensor_api_v1_campaigns_campaign_id_stations_station_id_sensors_sensor_id_measurements_measurement_id_put

        Update Sensor
        """
        pass


if __name__ == '__main__':
    unittest.main()
