# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.api.uploadfile_csv_api import UploadfileCsvApi


class TestUploadfileCsvApi(unittest.TestCase):
    """UploadfileCsvApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UploadfileCsvApi()

    def tearDown(self) -> None:
        pass

    def test_post_sensor_and_measurement_api_v1_uploadfile_csv_campaign_campaign_id_station_station_id_sensor_post(self) -> None:
        """Test case for post_sensor_and_measurement_api_v1_uploadfile_csv_campaign_campaign_id_station_station_id_sensor_post

        Post Sensor And Measurement
        """
        pass


if __name__ == '__main__':
    unittest.main()
