# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.models.get_station_response import GetStationResponse

class TestGetStationResponse(unittest.TestCase):
    """GetStationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStationResponse:
        """Test GetStationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStationResponse`
        """
        model = GetStationResponse()
        if include_optional:
            return GetStationResponse(
                id = 56,
                name = '',
                description = '',
                contact_name = '',
                contact_email = '',
                active = True,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                geometry = upstream_api_client.models.geometry.Geometry(),
                sensors = [
                    upstream_api_client.models.sensor_item.SensorItem(
                        id = 56, 
                        alias = '', 
                        description = '', 
                        postprocess = True, 
                        postprocessscript = '', 
                        units = '', 
                        variablename = '', 
                        statistics = null, )
                    ]
            )
        else:
            return GetStationResponse(
                id = 56,
                name = '',
        )
        """

    def testGetStationResponse(self):
        """Test GetStationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
