# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.models.stations_list_response_item import StationsListResponseItem

class TestStationsListResponseItem(unittest.TestCase):
    """StationsListResponseItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StationsListResponseItem:
        """Test StationsListResponseItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StationsListResponseItem`
        """
        model = StationsListResponseItem()
        if include_optional:
            return StationsListResponseItem(
                id = 56,
                name = '',
                description = '',
                contact_name = '',
                contact_email = '',
                active = True,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                geometry = upstream_api_client.models.geometry.Geometry(),
                sensors = [
                    upstream_api_client.models.sensor_summary_for_stations.SensorSummaryForStations(
                        id = 56, 
                        variable_name = '', 
                        measurement_unit = '', )
                    ]
            )
        else:
            return StationsListResponseItem(
                id = 56,
                name = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testStationsListResponseItem(self):
        """Test StationsListResponseItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
