# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.models.measurement_create_response import MeasurementCreateResponse

class TestMeasurementCreateResponse(unittest.TestCase):
    """MeasurementCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeasurementCreateResponse:
        """Test MeasurementCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeasurementCreateResponse`
        """
        model = MeasurementCreateResponse()
        if include_optional:
            return MeasurementCreateResponse(
                id = 56
            )
        else:
            return MeasurementCreateResponse(
                id = 56,
        )
        """

    def testMeasurementCreateResponse(self):
        """Test MeasurementCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
