# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.models.sort_field import SortField

class TestSortField(unittest.TestCase):
    """SortField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortField(self):
        """Test SortField"""
        # inst = SortField()

if __name__ == '__main__':
    unittest.main()
