# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstream_api_client.models.station_type import StationType

class TestStationType(unittest.TestCase):
    """StationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationType(self):
        """Test StationType"""
        # inst = StationType()

if __name__ == '__main__':
    unittest.main()
