# coding: utf-8

"""
    Upstream Sensor Storage

    Sensor Storage for Upstream data

    The version of the OpenAPI document: 0.0.1
    Contact: wmobley@tacc.utexas.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StationType(str, Enum):
    """
    StationType
    """

    """
    allowed enum values
    """
    MOBILE = 'mobile'
    STATIC = 'static'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StationType from a JSON string"""
        return cls(json.loads(json_str))


